### ISSUE TITLE
Problems with TriggerAttackRelease code

### ISSUE THREAD

**Issue by lukephills** [BlokDust/BlokDust#110]
Check line 321 of source.ts

I moved your 'else if' to the bottom as it stopped the particle collisions from triggering samplers.

Check: `this.PowerConnections!==undefined` because it always returns true.

**Comment by Whitevinyl** [comment]
It's for Power type source blocks - have labelled now. Was hoping to do:
if (this instanceof PowerSource) {}
but that seems to make a feedback loop in the referencing.
