### ISSUE TITLE
AUDIO: Intermittent Envelope release failure

### ISSUE THREAD

**Issue by Whitevinyl** [BlokDust/BlokDust#115]
When you fixed #99 this was fixed (it's what I was referring to in #99's comments), but whatever's changed in the recent Tone update has made it return.

http://localhost:8000/default.html?c=116voEdFXK&t=volbb

if you let this play a while you'll hear some of the release methods fail. I'd looked hard at it before and everything seems correct right into the envelopes triggerRelease method, but just bugs out every now and then for some reason.

**Comment by lukephills** [comment]
Yeah I contacted Yotam about the clicking and he said the most efficient way to use trigger attack is to pass in the time 'triggerAttack('+0.01') instead of leaving the parameters empty and not to use now(). So I updated our TriggerAttack methods and the clicking went away. There might be a more effecient way to handle the Releases too but I've just had the example on a loop for a few minutes and I couldn't hear the release failing.

Here's the convo with Yotam:
https://github.com/Tonejs/Tone.js/issues/79

**Comment by Whitevinyl** [comment]
I just ran it again and had the release fail pretty quickly. It was totally fixed but it's been happening again since I last did a bower update and it installed a Tone update. Seems pretty regular so I'm not sure what's up

**Comment by Whitevinyl** [comment]
Ah is it that you rolled back the envelope and rolled forward again once you got the attack fix from Yotam? Maybe we should call release the same way

**Comment by lukephills** [comment]
Yeah I rolled the envelope back and then forward again with attack fix. I'll ask about the release. I can't seem to recreate it though, weird.

**Comment by lukephills** [comment]
I tried triggerRelease('+0.01') and I didn't hear any release fails either but then this created nasty clicks on release when you attach and detach power blocks. It basically made https://github.com/BlokDust/BlokDust/issues/112  a lot worse so I won't commit that yet.

**Comment by Whitevinyl** [comment]
OK, I'll try and make a more defined test in the meantime, as sometimes it can go for a few minutes without doing it, but might be best to look at this one next time we meet

**Comment by lukephills** [comment]
Yeah think so. I need Ed's help with the attach/detach problem too. So maybe this is a good one to work on next weekend.

**Comment by Whitevinyl** [comment]
this can also be recreated with either midi or computer keys set to poly attached to a tone block with envelope I've just found. 
arpeggiating slow chords and leaving a few seconds between each burst is a good way to listen for it.

**Comment by Whitevinyl** [comment]
consolidating envelope issues to #163
