### ISSUE TITLE
POWER: Stopper Block

### ISSUE THREAD

**Issue by lukephills** [BlokDust/BlokDust#118]
Here's an example when a stopper block would be useful:  
http://localhost:8000/default.html?c=C0SE81LFXK&t=svars%C3%B8

You're using toggle switch to turn of an on a laser but if the laser is spinning it will turn it's own switch off stopping the sequence. A stopper block should stop lasers and particles passing through.

What do you recon @Whitevinyl ?

**Comment by Whitevinyl** [comment]
Yeah definitely - this is the spacey looking block on the old spec, adding it to this milestone.
Something you can do for the time being is toggle a second laser which points at that laser, the second one having a longer range so that the rotating one can't reach the toggle

**Comment by lukephills** [comment]
Ah yeah, the black hole-looking one I remember.
