### ISSUE TITLE
UI: Add download button and filename to Recorder

### ISSUE THREAD

**Issue by lukephills** [BlokDust/BlokDust#128]
Filename is set like this:    
`Recorder.Filename = "BlokdustRecording.wav"`

And to download:   
`Recorder.DownloadRecording()`

**Comment by Whitevinyl** [comment]
Have added the download button, the function isn't following through to recorderJS though - here's the error when I call DownloadRecording():
Uncaught TypeError: this.Recorder.setupDownload is not a function
