### ISSUE TITLE
CONNECTIONS: Post effect update issue

### ISSUE THREAD

**Issue by Whitevinyl** [BlokDust/BlokDust#132]
Example case:

create a tone source, attach to it first an effect like chorus or filter.
Attach to it second an effect like delay or reverb.

Then drag a second tone source so that it connects with the same effects, and then drag it away again.

Playing the first source now you can hear that the delay or reverb is no longer in the chain.

**Comment by lukephills** [comment]
Fixed this with the new accumulative audio connections method. All blocks that are connected are added to a single `AudioChain` which contains a list of Connections. All effects in the chain are connected in series and the Sources are connected to the first effect in the series.

20bf66b4a1
