### ISSUE TITLE
FEATURE: Save general settings to local storage ( theme selection etc )

### ISSUE THREAD

**Issue by Whitevinyl** [BlokDust/BlokDust#161]

**Comment by lukephills** [comment]
First time visiting. We don't want to show tutorial to people who've opted out already

**Comment by lukephills** [comment]
SeenTutorial: boolean
ThemeSelected: Theme

**Comment by Whitevinyl** [comment]
Utils.Storage.set(this.CompositionId, this._SessionId, 315360000, Utils.StorageType.local);
