### ISSUE TITLE
AUDIO: Envelope: Mixed issues - rewrite Tone.Envelope to pass blokdust tests

### ISSUE THREAD

**Issue by Whitevinyl** [BlokDust/BlokDust#163]
Consolidating known issues here:

1. Intermittent release failure
    may be fixed but needs further testing, best test is a laser loop using sources with envelopes
    #115 

2. Multiple sources sharing envelope failure
    new issue, may be intermittent, needs testing

3. Audible clicking when triggered rapidly
    firing particles with v. low delay time you can hear the release be interrupted, relatively recent

**Comment by lukephills** [comment]
- [ ] TEST 1: SINGLE ENVELOPE AND KEYBOARD
http://blokdust.azurewebsites.net/?c=3w5i8M5VXK&t=envelope%20test
TEST: Play notes on a keyboard in quick succession retriggers envelope attacks
EXPECTED: On each new note triggered the previous note should immediately stop and the new note should start the attack portion
CURRENTLY: On each new note triggered the previous note stops immediately but the note ignores the attack portion.

**Comment by lukephills** [comment]
- [ ] TEST 2: ENVELOPE CONNECTED TO TWO SOURCES    
http://blokdust.azurewebsites.net/?c=6wkngV5VXK&t=envelope%20test2

TEST: Play notes on the keyboard

EXPECTED: Both Tone and Noise volumes should ramp up on key pressed and ramp down on key release.

CURRENTLY: Both Tone and Noise volumes ramp up on key pressed as expected but do not ramp down on key release. Instead, the volume cuts out completely.

**Comment by lukephills** [comment]
- [ ] TEST 3: FAST LASER LOOPING TONES WITH INDIVIDUAL ENVELOPES    
http://blokdust.azurewebsites.net/?c=bVtXwQ6VXK&t=envelope%20test%203

TEST: Adjust speed of laser rotation to test intermittent release failure

EXPECTED: Laser should loop through all tones and their envelopes should be heard

CURRENTLY: All envelopes are present but has on rare occasion made a loud bang sound and given this error:    
`Uncaught InvalidAccessError: Failed to execute 'linearRampToValueAtTime' on 'AudioParam': Time must be a finite non-negative number: -310.034`

**Comment by lukephills** [comment]
- [ ] TEST 4: FIRING PARTICLES WITH V.LOW DELAY TIME    
http://blokdust.azurewebsites.net/?c=jhbUHX6VXK&t=envelope%20test%204

TEST: Let Particle Emitters fire at all sources. Press and hold on a source.

EXPECTED: All particles should trigger the beginning of the attack portion on every collision hit. Pressing and holding a source whilst being fired should allow the full envelope arch to be heard but then on mouse up the particles should carry on trigging the attack portion.

CURRENTLY: All particles trigger the attack portion as expected. When a source is pressed the envelope arc is heard but on release the particles carry on triggering from where the envelope left off.
