### ISSUE TITLE
MIDI & COMP KEYS: release & trigger conflict

### ISSUE THREAD

**Issue by Whitevinyl** [BlokDust/BlokDust#191]
Issue we were having before where releasing a key at the same time as pressing another, kills an audio sample. Consecutive triggers timed the same way don't start a new sample

**Comment by lukephills** [comment]
This is related to #191

**Comment by lukephills** [comment]
I don't think it is the same issue as before. I'm having trouble pinning it down. It's a lot harder to recreate than before. That 'conflict gap' seems very small.

I think we'll have to abstract this problem out to a separate example and ask Yotam.

**Comment by lukephills** [comment]
Test using two voices. As soon as triggerRelease is called switch to 2nd voice and vice versa.

**Comment by lukephills** [comment]
Submitted issue to Tone. In the meantime reverted back to an older simpler functionality which doesn't use Tone.TimelineEvents.

https://github.com/BlokDust/Tone.js/commit/569d2d31e3b854a2f200d43ac922f189f49725d8
