### ISSUE TITLE
LOAD FROM SAVE: mixed errors 

### ISSUE THREAD

**Issue by Whitevinyl** [BlokDust/BlokDust#192]
http://localhost:8000/?c=x9Y8VgzJXK&t=vollok

unexpected token in blob for some saves

**Comment by Whitevinyl** [comment]
All blocks:

http://localhost:8000/?c=DmZRfgBSXK&t=all%20blocks

pos2 missing on void block, creates error for blocksprites

**Comment by Whitevinyl** [comment]
http://localhost:8000/?c=9X4Pw1cVXK&t=wobble%20glide

newer example with same issue

**Comment by edsilv** [comment]
For reference, needed to clear local storage of old saves
