### ISSUE TITLE
AUDIO: Tidy parameter ranges - normalise volumes etc

### ISSUE THREAD

**Issue by Whitevinyl** [BlokDust/BlokDust#208]
just go through blocks and bring down top level on blocks like Autowah and Chomp

**Comment by Whitevinyl** [comment]
Would also be cool if the pitch shifter went a whole octave up and down, otherwise to achieve this requires 2x the block currently

**Comment by Whitevinyl** [comment]
Also can we add a mix param to the pitch shifter? would be cool to blend with the original signal for harmonisation.

**Comment by lukephills** [comment]
Added mix and whole octave shifting.  70d0512

**Comment by lukephills** [comment]
Lowered Chomp gain bc1ce9b2d3b

**Comment by lukephills** [comment]
I'm not sure what to change for the AutoWah. Like a filter, it accentuates certain frequencies so it completely depends on the source sound.
