### ISSUE TITLE
HTTPS: Secure server needed to run Microphone / getMediaSource()

### ISSUE THREAD

**Issue by edsilv** [BlokDust/BlokDust#212]
Implement https using letsencrypt. Redirect to https http://blog.smarx.com/posts/redirecting-to-https-in-windows-azure-two-methods

**Comment by Whitevinyl** [comment]
https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-14-04
