### ISSUE TITLE
TONESOURCE: couple of issues with setting "Note" when hooked to keyboard 

### ISSUE THREAD

**Issue by Whitevinyl** [BlokDust/BlokDust#218]
Setting the Note setting in the options panel does unexpected things to the resultant pitch when playing keys hooked up to the Tone block. Holding a key down while changing it is fine, but repeat triggers have varied results.

Also powering a Tone block after it has been played with keys leaves the note heard as the last one played on keys, instead of what's set in options.

**Comment by Whitevinyl** [comment]
First issue seems fine with playback rate on SC block btw, although the second one is consistent

**Comment by Whitevinyl** [comment]
Third issue on this and a weird one. Set a Tone's Note setting to any note outside of octave 4. then, disconnect or connect a block. Any block. They don't need to be attached at any point to the Tone block we're observing.
Doing this always sets the Tone's note to be in octave 4.

**Comment by lukephills** [comment]
> Setting the Note setting in the options panel does unexpected things to the resultant pitch when playing keys hooked up to the Tone block. Holding a key down while changing it is fine, but repeat triggers have varied results.

This is because the note setting is acts as a transposition. C4 is default setting but if you set to C#4 all the notes of the keyboard are 1 step higher.

> Also powering a Tone block after it has been played with keys leaves the note heard as the last one played on keys, instead of what's set in options.

If you play the keyboard and then power the tone it *should* play the note set in options. If you're playing the keyboard whilst a power is connected it will hold all the notes as you play them.

**Comment by lukephills** [comment]
After testing the soundcloud, it seems broken. Changing playback rate with a keyboard connected. Then disconnect keyboard and change playback rate again. Playback rate no longer has an effect.

**Comment by lukephills** [comment]
As for the third, I'm putting that in a separate issue so it's easier to keep track

**Comment by Whitevinyl** [comment]
Yeah I mean the transposition isn't working, only when holding keys down, otherwise it creates inconsistent pitch. Sometimes transposing down makes the pitch go up, and it's always in the same octave range.
Definitely playing the last keys note & not options note for me too - this is with computer keys & a tone block.

**Comment by lukephills** [comment]
Can you give me some steps to recreate?

**Comment by Whitevinyl** [comment]
Yeah, just create a Tone, create Computer Keys and connect to Tone.
Open Tone options, play a few keyboard keys to hear the pitch, click anywhere on the Note slider.

Clicking around what I'm setting in no way corresponds to what I'm hearing. If I just repeatedly play one note while sliding the note slider down, the pitch I hear goes up at some points and down at others.

**Comment by lukephills** [comment]
Aha!! I see, it is related to the 3rd issue above. Its always resetting itself to octave 4.

**Comment by lukephills** [comment]
Okay I recon I've fixed this now. Can you check your end?

I've renamed ToneSources note setting ```baseFrequency``` to ```transpose``` . I think this makes more sense as the number (currently -48 -> 48) isn't a frequency.

**Comment by Whitevinyl** [comment]
Hmm ha, well yes but also no! If I'm using the slider in-between playing it's fixed, but there's 3 more issues now:
- sliding while playing has no effect
- changing detune with some transpose set, audibly resets transpose
- changing transpose and clicking the block makes no audible transposition, plays last keyboard note.

I'm tempted to say leave it and let's just tackle the controller refactor before launch, if I set up what I have in mind it'll probably take a day and I think we'll be glad of it once it's there. What do you think?

**Comment by lukephills** [comment]
Haha yeah I think its fixed now. I forgot to commit an import line. 

As for controller refactor, yeah go for it!
