### ISSUE TITLE
MIDI: Starting app with MIDI controller connected throws error. Cannot read property 'MainScene' of undefined

### ISSUE THREAD

**Issue by Whitevinyl** [BlokDust/BlokDust#220]

**Comment by Whitevinyl** [comment]
Also: loading BD with a device already plugged in logs a promise error in console, although I can't see any problems come from it.

**Comment by lukephills** [comment]
The error is because it's trying to send an App.Message to say midi is connected. I think at that stage it can't read App.MainScene in App.Message. 

In the midi logger I am checking to see if App.Message is a function before calling it and I something has changed with App.MainScene

**Comment by Whitevinyl** [comment]
Ah ok, it's not App.MainScene any more, MainScene is a child of Stage, so I think it'd be App.Stage.MainScene. Would that affect the regular disconnection message though? Everything else about the message is fine, just it says connected when it should read disconnected.

**Comment by lukephills** [comment]
No I've fixed the disconnection message now and committed that change here 357cad6

The 'loading BD with a device already connected' error is the problem I was taking about but actually I'm not getting the error any more. Feel free to reopen if you still notice it.
