### ISSUE TITLE
POWER: some connection issues

### ISSUE THREAD

**Issue by Whitevinyl** [BlokDust/BlokDust#234]
On this save:
http://localhost:8000/?c=Vk6NpC3ne&t=vox%20mutate

1. the WaveGen isn't triggering despite being powered (reconnecting works)
2. disconnecting the microphone doesn't disable it

**Comment by lukephills** [comment]
The wavegen is getting triggered, however at the point it's being triggered it's own buffer hasn't finished loading. I think the wavegen needs to trigger when ready like the soundcloud does.

Here's a simpler example: http://localhost:8000/?c=41iYI1k6l&t=Sjidust

**Comment by lukephills** [comment]
Have changed MaxOperations to 1 for first testing.

**Comment by Whitevinyl** [comment]
Ah ok, thought it was like soundcloud - will take a look

**Comment by Whitevinyl** [comment]
Have fixed the Samplegen (WaveGen) but the Mic issue remains. I noticed that dragging the Mic to disconnect it works, but dragging the power block away leaves the Mic powered.

**Comment by Whitevinyl** [comment]
Fixed this in the Controller refactor.
