### ISSUE TITLE
BLOB LOAD: trying to load a non-existent compositionId never times out

### ISSUE THREAD

**Issue by Whitevinyl** [BlokDust/BlokDust#237]
Doesn't generate a useable error and prints this to console:
GET http://files.blokdust.com/compositions/NJOLfMp2e?t=1457810511547 403 (Forbidden) 
jquery.js:8630

Hangs on "Loading Scene"

**Comment by edsilv** [comment]
This seems to be a problem with App.Message. The error is getting caught, and App.Message is getting called, but nothing appears

**Comment by Whitevinyl** [comment]
Oh mainscene probably doesn't exist for the message to draw to. will test and see if it can be deferred.

**Comment by Whitevinyl** [comment]
No, removing the App.Message lines makes no difference.
