### ISSUE TITLE
TONE: setValueAtTime on Tone.js Param.js

### ISSUE THREAD

**Issue by Whitevinyl** [BlokDust/BlokDust#249]
Hooking computer or midi keys to a source, will trigger correctly once but any keypress afterwards generates:

Param.js:148
Uncaught TypeError: Failed to execute 'setValueAtTime' on 'AudioParam': The provided float value is non-finite.

Similarly altering a Tone block's transposition plus a bunch of other stuff.
Not sure where this has happened but is on the dev deployed version

**Comment by Whitevinyl** [comment]
This also breaks web audio across tabs which is pretty weird, Chrome update maybe?

**Comment by lukephills** [comment]
It's seems to be an issue with Tone.Param.prototype.exponentialRampToValue.

Looking into a fix for Tone. In the meantime, have switched to linearRampToValue and no errors.

**Comment by lukephills** [comment]
Closing this as linearRamp seems to be working. Will test exponential function another time
