### ISSUE TITLE
GUIDE: Move wordpress location to Web server

### ISSUE THREAD

**Issue by Whitevinyl** [BlokDust/BlokDust#255]
Dev & Live servers will just be for the app etc.

**Comment by lukephills** [comment]
- [ ] WP on web server 146.185.135.65

- [ ] guide.blokdust subdomain maps to /guide directory

- [ ] Remove WP from dev server 82.196.9.128

**Comment by lukephills** [comment]
https://www.digitalocean.com/community/questions/extra-wordpress-website-on-a-sub-domain-using-nginx-lemp

https://www.digitalocean.com/community/tutorials/how-to-set-up-and-test-dns-subdomains-with-digitalocean-s-dns-panel
