### ISSUE TITLE
ENVELOPE: general clicking - look at using stripped back BD version 

### ISSUE THREAD

**Issue by Whitevinyl** [BlokDust/BlokDust#257]

**Comment by lukephills** [comment]
Stripped back Tone.Envelope to Tone.SimpleEnvelope. Also stripped back Tone.Source, Tone.Sampler and Tone.Player.

Closing this as envelopes work again. Starting a [new issue](https://github.com/BlokDust/BlokDust/issues/270) (#270) to look at stripping back all tone classes specifically used in Blokdust
