### ISSUE TITLE
UI: Load SoundCloud sample interface

### ISSUE THREAD

**Issue by Whitevinyl** [BlokDust/BlokDust#26]

**Comment by lukephills** [comment]
I will get the functionality up a running first.

Search should filter creative commons songs or any tagged 'blokdust'.

Might need to filter by length (especially for granular)

**Comment by lukephills** [comment]
Added soundcloud search function: 1b4e3e

You can get an array of tracks by doing this. The first parameter is the search query and the second is the callback when it's done searching. tracks is an array of track objects containing all it's information.

```
SoundCloudAudio.Search('your search query', (tracks) => {
   tracks.forEach((track) => {
        console.log(track);
    });
);
```

Currently haven't found away to make it search 'cc' OR 'tags' which is what we need. Currently it'll only bring back tracks with both filters. Will look into it. 

This should be good enough to get started with the UI.

**Comment by Whitevinyl** [comment]
Ah awesome - I think that's how it should work anyway, it brings back all possible results from both CC & Tags and the filtering is fixed behind the scenes rather than user selectable.

Just that different blocks search for different tags and duration filters. Will move onto this shortly.

**Comment by Whitevinyl** [comment]
Left to do on this:
- Type editable search 
- Extend search function to combine multiple queries 
- Add a "no search results" case 
- Add track load error cases and timeout* 
- Open with default local files

* SoundCloud have an issue where every now and then a track doesn't have the right CORS headers. I don't know that there's any callback we can check so we'll just have to timeout a load after so long and roll back to the previous track info.

**Comment by Whitevinyl** [comment]
UI done, moving functionality updates to fresh issue
