### ISSUE TITLE
GUIDE: Image upload fails (destination folder)

### ISSUE THREAD

**Issue by Whitevinyl** [BlokDust/BlokDust#267]
Tried uploading a featured image and keep getting this error:

The uploaded file could not be moved to wp-content/uploads/2016/03.

**Comment by Whitevinyl** [comment]
Also unable to install a plugin for the custom post order, said directory didn't exist

**Comment by lukephills** [comment]
Was a file permissions problem. Is working now and have copied the custom post order plugin from previous install
