### ISSUE TITLE
Sampler Reverse freezes app until it's finished

### ISSUE THREAD

**Issue by lukephills** [BlokDust/BlokDust#269]
If you have some particles firing on the stage and you reverse a sample all the drawing freezes until the reverse has finished. Do you think this could work asynchronously instead?

**Comment by Whitevinyl** [comment]
Yeah I noticed this recently, it's ok on small samples but long ones hog the stack.
Can look at trying the timeout trick, but I'd like to look at webworkers to do some proper asynchronous stuff with waveform manipulation.

- Analysing waveform images
- SampleGen generation
- Wave Reverse

would all benefit.

**Comment by lukephills** [comment]
Yes, have been using Worker Timerson another project for keeping web audio running in a closed tab and it works great. https://github.com/chrisguttandin/worker-timers

**Comment by Whitevinyl** [comment]
Fixed this one a while back, missed the issue
