### ISSUE TITLE
LFO: connecting lfo's and creating voices at the same time mismatch

### ISSUE THREAD

**Issue by Whitevinyl** [BlokDust/BlokDust#271]
1. Create a controller and set it to polyphonic
2. Create a Scuzz and place it near the controller
3. Create a Tone source and connect it to both at the same time

The LFO is only connected to the first of Tone's sources, as (I think) the rest hadn't been set up yet via the CreateVoices() function.

**Comment by lukephills** [comment]
Bug can actually be recreated by connecting a Tone and a Scuzz together. Then adding a keyboard (set to poly).

Can also be recreated using a Vibrato or Envelope instead of a Scuzz.

**Comment by lukephills** [comment]
Fixed in 2c3b2ae7b63d28
