### ISSUE TITLE
LFO/SCUZZ: Use audioBufferSourceNode.detune for the Players

### ISSUE THREAD

**Issue by Whitevinyl** [BlokDust/BlokDust#272]
So I made a recent update adding a SignalToValue component.

We had an issue before where attaching an LFO to a SamplerBase block meant that it's playback rate would be hogged by the LFO, and pitching notes via a controller no longer worked as expected.

LFO output is linear while playbackRate is a ratio so there's some mismatch there as well.

Adding this SignalToValue component to buffer-type sources fixes the LFO issue at slow rates. The LFO connects to it instead of playback, and it spits the signal value back out to javascript, and we can use that to update pitches in the same way as transpositions. The Vibrato sounds good and as expected now, and multiple LFOs will work together.
The Scuzz doesn't fare so well at the moment, because it's rate/frequency is so high that it far exceeds the framerate we're polling the values at.

I see the SignalToValue as temporary, the newer Web Audio API spec has added detune to buffer nodes, like oscillators already have, but that's not in the browser yet.

With the Scuzz I'm wondering what to do with it at the moment. Do we:

- Make it so that Vibrato does use the SignalToValue, but Scuzz doesn't? and just treat it as a block that totally messes with pitch.

- Convert the 'Pulverisation' to be lower if the source is a buffer type? Currently the Scuzz sounds pretty good with high 'Power' and lower 'Pulverisation', the depth doesn't seem to be a problem. I think setting the 'Power' to around 5000 as the default would be good in all cases as well.

- Something else?

**Comment by lukephills** [comment]
I'm not sure. Does the Tone block use the SignalToValue too? I like how you could get nice metalic sounds using the scuzz, but it seems like it's missing the overdrive quality it had.

**Comment by Whitevinyl** [comment]
Ah no I've left the Tone the same, the LFO just plugs into it's detune. But for Buffers, they currently don't have a detune, so this replaces it until it's there.

You can hear the difference against the Live deploy:

- If you hook a controller up to a SoundCloud block.
- pick a melodic sample (if you search "cello bow" and look for the track by blokdust.)
- connect to Vibrato

On Live, when you play keys you'll hear the transposition and pitch are wrong, but is fixed on Master.
The Scuzz definitely sounds better on Live though, even with the pitch being wrong. So I think I'm leaning toward the first option, using it for Vibrato but not Scuzz.

**Comment by Whitevinyl** [comment]
Actually I've been trying to find more info on buffer detune, and I think it may be implemented now in Chrome and Firefox: https://developer.mozilla.org/en-US/docs/Web/API/AudioBufferSourceNode/detune

We could try exposing it in the Tone SimplePlayer - just copy from the Oscillator. Downside then would be  no Safari, but would sound better if it works.

**Comment by lukephills** [comment]
Yes lets use the new detune node. Possibly I could make a fallback but for safari.
