### ISSUE TITLE
MOMENTARY: extend function & rename to "Pulse Power"

### ISSUE THREAD

**Issue by Whitevinyl** [BlokDust/BlokDust#274]
Writing the wiki pages has been making me think a lot about each block functionality.

With the Momentary Power, it currently relays a pulse, same length as a particle powers for. When I think of a real life momentary switch, I think of one which can be held down - a "push-to-make". This might be useful in BD in future, i.e if a Momentary is powered by a laser beam, it continues relaying power until the beam stops or passes through the block.

Rather than do any work like that at this stage, I'm wondering if we keep this switch working with a pulse, but we rename it "Pulse Power", leaving us open to create a held momentary in future if we want.

This also makes me wonder if we give it an extra option which is its own pulse length independent of the global one. So when powered, it relays that power for a length adjustable via slider, holding down chords, powering lasers for a set time etc.

Thoughts?

**Comment by lukephills** [comment]
Yeah I really like this. Makes a lot of sense. I'm happy to make the changes
