### ISSUE TITLE
TONE.js: Master Volume doesn't work in loaded composition

### ISSUE THREAD

**Issue by Whitevinyl** [BlokDust/BlokDust#284]

**Comment by Whitevinyl** [comment]
There doesn't seem to be anything wrong with the slider, it works when not loading from comp.

When we load from a composition we call .rampTo() on the Master.volume to fade the audio in.
this is on MainScene.ts line 781.
Commenting this out makes the volume slider work again. I've tried calling the ramp elsewhere and same thing, it breaks the volume. So I'm thinking maybe it's a Tone thing, Tone.Master, Tone.Volume or Tone.Gain?

**Comment by lukephills** [comment]
Fixed the Master Volume slider for loaded compositions but need to revisit this bug when doing #270
