### ISSUE TITLE
AUDIO: Saved/loaded block settings - mixed

### ISSUE THREAD

**Issue by Whitevinyl** [BlokDust/BlokDust#287]
Chorus & Phaser - the Rate setting is not getting saved
Autowah - Attack & Release not saving
Chopper - Rate & Waveform not saving
Pitch Shifter - Mix not saving

The Autowah one is a little strange, both the attack & release need to be bumped after it's loaded, to hear either revert to what they should be.

**Comment by lukephills** [comment]
Hey Luke, 

Do you think this maybe a cross version issue? I can't recreate it. They seem to saving okay. 

Here's a save with all params set to left-most values:  
http://localhost:8000/?c=4yif6CNzW&t=Knab%C3%B8%20Volb%C3%B8

Have you got an example save?

**Comment by Whitevinyl** [comment]
Yeah the above actually works as a perfect example for me - I should have worded a little differently, the settings get saved, but it doesn't load the audio components with those settings.

Adding a power block to the above, I can hear the Chopper pulsing, but I shouldn't because it's set to zero. Moving the slider slightly will update it to how it should sound. Same with the others, e.g it's loading up pitch-shifted although the Pitch Shifter mix is set at zero.

**Comment by lukephills** [comment]
Cool, got it. I've fixed this now and checked the other blocks. 

For future reference these issues are because the Blocks weren't initialising their settings properly or not at all in `Init()`.

Note: The values should always be set using `this.Params`, not `this.Defaults`.
