### ISSUE TITLE
SOUNDCLOUD: Rename block? - Discussion

### ISSUE THREAD

**Issue by Whitevinyl** [BlokDust/BlokDust#291]
Was thinking about this block name and if we should rename it - for 2 reasons.
One I'm just not sure it's a great name, and there is a potential issue with it being named after the service. I mean I guess it's no different to having a web page, tab, or audio player titled SoundCloud, but still.

The main reason though is I'm thinking about future usage. If I'm ever sourcing samples, I don't really use SC for that, I go to www.freesound.org 
I've seen recently that freesound have updated their API, and it's basically very similar to the SC one. It would be nice in future to not just limit ourselves to SC, but I don't think we should have a duplicate block for each service we use, instead it would be nice if one block could be multi-service.
I'm not worried about figuring out how exactly that happens at the moment - whether searching automatically queries multiple API's, or if different sources are selectable, or something else.

But should we at least rename the SC block with something more generic so we're open to those options in future? Currently I don't have a better suggestion than "WebSample". Thoughts?

**Comment by lukephills** [comment]
Yes, seems like a good idea to me. We wouldn't want be stuck if something happened to Soundcloud and I like the idea of adding more audio services. 

I'm wondering whether we could just call it 'Sample'? Does it need 'web' in the title? Perhaps if we're adding local samples in the future this should be inside same block anyway since there shouldn't be any difference between a local sample and a web sample only where the sample is loaded from.

**Comment by Whitevinyl** [comment]
Yeah I think just calling it Sample would be better, and you're right, it'd be much nicer to build the local sample functionality into all sample-based blocks, with the SoundCloud search panel becoming a more generic sample loader panel.
One thing that is different between local & web samples from a user perspective is that local samples won't be shared, so we'd have to think on how best to differentiate in the load-from-save functionality, and also the messaging so that it's clear to a user if their samples won't be saved.
