### ISSUE TITLE
GUIDE: minor updates

### ISSUE THREAD

**Issue by Whitevinyl** [BlokDust/BlokDust#294]
- [x] SoundCloud block needs renaming to Sample
- [x] Momentary Power is now Pulse (and it's operation has changed)
- [x] Delay is now Stereo Delay
- [x] Email line can be changed to "Get in touch with us at:" or similar.
- [x] Make menu contents have a vertical scroll bar when overflow

**Comment by lukephills** [comment]
Updated stylesheet to allow menu to scroll vertically: https://github.com/BlokDust/BLOKDUST_GUIDE/commit/db071a9c06c37a51b4067d70e4f426a29d330963

Have pushed to the server but the change isn't there yet. Perhaps the server cache needs to be refreshed?

**Comment by Whitevinyl** [comment]
Oh cool, hmm, it looks like the theme has updated (because the contact message has changed, it was the old one still yesterday), but yeah I'm not seeing the scrolling - maybe something else is interfering with it in the css?

**Comment by Whitevinyl** [comment]
Looking at the style.css file I don't see the change in there, did it push properly?

**Comment by Whitevinyl** [comment]
scrap that, github did something weird and sent me to the wrong repo. yeah it is there, just not on the site

**Comment by Whitevinyl** [comment]
I think maybe we need to add a max-height to the menu panel for the overflow to kick in

**Comment by lukephills** [comment]
Fixed it. The functions.php file was specifying a version number for the stylesheet so it was getting style.css?ver=1.0 which was old. Changed it so it just gets style.css

**Comment by lukephills** [comment]
Does it work how you expected?

**Comment by Whitevinyl** [comment]
Ah cool, nice one - I think if we set it:
overflow-y: auto
Then it will only show when needed
