### ISSUE TITLE
MONO SAMPLE: attack/release overlap

### ISSUE THREAD

**Issue by Whitevinyl** [BlokDust/BlokDust#303]
Attaching an envelope to a sample block in monophonic, you can hear an overlap of the last notes release and the new notes attack.

Have made an example save here:
http://localhost:8000/index.html?c=4kVcxpFF-&t=Enl%C3%B6

you can hear the overlap on the sampleGen when you release one key and press another
If you put the envelope on the cello sample you can hear the click of the sample end

**Comment by lukephills** [comment]
I'm not sure how to get around this. When triggerRelease is called the sample is told to stop after the release time. If you triggerAttack within that release time you'll fade the volume of the sampler up and also the volume of the last triggered sample. 

We did talk about creating new Samplers on every trigger but that'd have to be for a later date.

**Comment by Whitevinyl** [comment]
Is there a way to tap into the individual samples within the sampler? So that in monophonic, when TriggerAttack is called, we call cancelScheduledValues() and set a short release time on all active samples except the new one?

Yeah it'll definitely be better once we get to that refactor.

**Comment by lukephills** [comment]
Yeah well we do cancelScheduledValues() which stops the last triggered notes fade out. Thing is stop(atReleaseTime) has already been called. As far as I know you cant go back and make it stop instantly.

**Comment by Whitevinyl** [comment]
Ah right ok, does that mean that attack is being re-called on those samples then? or is it that each of those samples doesn't have it's own envelope - there's just one for that sampler voice?

**Comment by Whitevinyl** [comment]
If it's the latter, I'm thinking it'd be worth a shot to try wrapping those samples with individual gains/envelopes so we have control over stopping them.

This I think would also help fix a lesser bug with reversing a sample which is already playing/powered acting a little funny.

Let me know if you think you'll have time to try it over the next day or 2, otherwise I might try and look at it tonight.
Currently just sorting the tester list so we're ready to go, but happy to hold off 'til Wednesday morning UK before we send it out.

If it doesn't work out or we don't get time, it might be worth us considering opening with poly as the default, and mono selectable, as currently that'd make the best first impression with sample blocks.

**Comment by lukephills** [comment]
It's one envelope for each sampler. Every time a sample is triggered a buffersource node is created and started and then stopped. I'm working today and tomorrow so only have a bit of evenings to look at it. Feel free to have a tinker

**Comment by Whitevinyl** [comment]
OK I've done a fix for this in Tone's SimplePlayer and it's sounding much better. There's a hardcoded release time which can be tweaked, but i'm seeing that as temp until we look at the refactor.

**Comment by lukephills** [comment]
Awesome, well done!
