### ISSUE TITLE
AUDIO: master level compression

### ISSUE THREAD

**Issue by Whitevinyl** [BlokDust/BlokDust#310]
I thought we had a compressor but looking I can't see one.

It just occurred to me that we definitely need a level limit before launch. People could potentially make malicious creations and share very damaging auto-playing audio-levels.

As a test I tried to make an obnoxiously loud & piercing sound.

UNDER NO CIRCUMSTANCES WEAR HEADPHONES WHEN OPENING THIS
https://blokdust.com/?c=E1FRz3AY-&t=No%20Headphones!

have headphones plugged in, put your comp volume at it's lowest level and just place some (cheap) headphones away from you. If you use the keyboard you'll see how loud it is. And it could probably go louder.
Strangely with laptop speakers it's fine (at least on my machine), they seem to auto-compress, but not so for headphone jacks.

**Comment by lukephills** [comment]
Might be too much compression let me know what you think.

**Comment by lukephills** [comment]
As an extra safety measure we could use the Meter to detect audio above 0db and mute it until the level is reduced.

**Comment by Whitevinyl** [comment]
Cool nice one, yeah I think it could probably come back some on the compression level/ratio if that's tweakable, can hear it come into effect pretty quickly when messing with EQ, but that's definitely capped that max level nicely.

Yeah could potentially add a meter check, I think we're pretty safe with a compressor, but the meter's already in so could use that as well. Could also try dropping the level by the amount of spill over 0db in place of muting.
I think the meter runs on javascript time, so it's not as precise at catching stuff as the signal processing is, but I'm not sure whether that means it is/isn't useful for this.

**Comment by lukephills** [comment]
Reduced the ratio and threshold while still capping the max level.
Potentially we could look at other audio level safety features but I think that's for another issue/release.
