### ISSUE TITLE
Move the default TriggerAttackRelease duration setting to App.Config

### ISSUE THREAD

**Issue by Whitevinyl** [BlokDust/BlokDust#35]
We define a global pulseLength which is the small amount of time a note is sustained when triggered via particle or other non-continuous power source

**Comment by lukephills** [comment]
Will add this PulseLength setting to App.Config and change line 289 of Source.ts inside the `TriggerAttackRelease` method.

`if (!duration) duration = "4n";`
`if (!duration) duration = App.Config.PulseLength;`

**Comment by lukephills** [comment]
fixed in 49bf2702e4d98
