### ISSUE TITLE
Chorus feedback param not working & LFO's are pulsing

### ISSUE THREAD

**Issue by lukephills** [BlokDust/BlokDust#60]

**Comment by Whitevinyl** [comment]
I think it is working but the range needs increasing - but probably not worth looking at til the modulation issue is sorted. If you set the rate & time to max, and depth between 0.1 - 0.3, you can hear the feedback affecting the high end. We may want to be able to set negative feedback like other chorus effects - depends how this one works in Tone. 

www.whitevinyldesign.com

**Comment by lukephills** [comment]
Yeah you're right. I tried out the latest version of tone to see if the modulation fixed, but it didn't make a difference. I'm gonna try a looking at a really old tone version and see if we can get it back to sounding the way it used to.

**Comment by lukephills** [comment]
Submitted another issue to Yotam https://github.com/TONEnoTONE/Tone.js/issues/70
