### ISSUE TITLE
Missing Blocks in saving/loading

### ISSUE THREAD

**Issue by Whitevinyl** [BlokDust/BlokDust#92]
To try and nail this we should list all cases of this occuring below.
Include the share URL and details of what's missing and/or any other activity that lead up to the save.

**Comment by Whitevinyl** [comment]
http://localhost:8000/default.html?c=iMbXdbGAXK&t=malkla

5 blocks, 1 missing.
missing block is Granular.
Granular was connected to all blocks.
Both computer and midi keyboard blocks had been created and deleted before save.

**Comment by lukephills** [comment]
What happens if you try to recreate this (as close as possible) in a new session?

**Comment by lukephills** [comment]
One thing that stands out to me so far is that the missing blocks seem to be the blocks that have most recently been changed. So far switches and granular. Maybe because there is a difference between live versions and local versions?

**Comment by Whitevinyl** [comment]
http://localhost:8000/default.html?c=w0tKgrhEXK&t=v%C3%B8t%C3%B8

28 blocks, 1 missing.
missing block is Power.
Power was connected to no blocks and positioned near the centre.
No blocks had been deleted.


A second bug exists here where the bass is twice as loud as when saved. Adjusting the existing Gain block brings the volume back into range.

**Comment by lukephills** [comment]
I think there must be a default param issue with either one of those bottom blocks. @edsilv how can I get the json file so I can have a look at what's being loaded in?

**Comment by Whitevinyl** [comment]
Have fixed the Gain bug, was an error in how it was set, convolution too.

Can we make sure these saves don't get deleted? Need them to figure this out

**Comment by lukephills** [comment]
Okay I recreated this too. Here are the steps to repeat:

1. Load Luke's example, 
2. attach a power block to the laser in the middle. 
3. Save as new. 
4. Load it up the new generated link. The power block should be missing.

**Comment by lukephills** [comment]
<img width="236" alt="screenshot 2015-07-20 08 23 27" src="https://cloud.githubusercontent.com/assets/6436772/8771356/a2819456-2eb8-11e5-8ce1-119ca1d4d841.png">


The Laser is a Source block and should be adding the Power to its internal list of effects.

**Comment by Whitevinyl** [comment]
Yeah I think once a save breaks, consecutive changes are always likely to have missing blocks. In the original the power source wasn't connected to anything.
Just tried a couple of different variations where other blocks disappeared with no obvious relation, one was a power block connected to a new Tone block, another was an unconnected Convolution (other unconnected effects in the same save remained).

**Comment by lukephills** [comment]
It's quite hard to understand whats going on in the Serialization, some comments would probably be helpful.

All I can tell is that on line 59 of `_SerializeBlock(block, parentBlock)` where the block is the Power and the parentBlock is an Object containing the Laser.
`var d = this._SerializationDictionary[block.Id];` returns true, which then breaks out of the function before the Power can be a serialized and added to the JSON object.

Any ideas @edsilv ?

**Comment by edsilv** [comment]
I think this is fixed now. If I open that example above and connect a power block, then save and load:

http://localhost:8000/default.html?c=4KHv4VrEXK&t=r%C3%B8kensorg

The power block is attached.

It was to do with how I was generating the block ids. Previously it was based on the number of blocks, which meant if you deleted one then added one, the new one would have a duplicate id. I'm now looping through all blocks to find the maximum id number and incrementing that. D'oh!
