### ISSUE TITLE
Oscillators clicking on attack - recent

### ISSUE THREAD

**Issue by Whitevinyl** [BlokDust/BlokDust#99]
Just noticed a clicking sound on attack with the oscillators

**Comment by lukephills** [comment]
It is an issue with the newest Tone release, specifically the Envelope class. I've reverted back to the original one - I'm not sure we need the updated Envelope. f96376d0c728

**Comment by Whitevinyl** [comment]
Ah cool, been trying to narrow down another bug with the envelope class so hoping this fixes that as well, will check in a bit
